name: my first CI pipeline

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: mypy
      run: mypy .

    - name: black
      run: black --diff --check .

    - name: isort
      run: isort --check-only .

    - name: flake8
      run: flake8 .
